### PR TITLE
Add A Logo

### LINKED ISSUE #5: Get an actually good logo.
There isn't a logo right now, if one of you guys wants to make one then go ahead by all means, I'll merge it.

### PR DESCRIPTION
**Pull request by david-webber**
fixes #5 

I've added a logo, let me know if you would like anything different?

image

image

### CODE REVIEW

**Comment by harshhh-dev** [comment]
Before merging, can you update your fork?

**Review by harshhh-dev — CHANGES_REQUESTED** [review]
```html
<head>
    <title>App Idea Generator</title>


    <link rel="stylesheet" href="./css/style.css" />

</head>```

I'd also like this to be the icon of the site :)

**Review by harshhh-dev — APPROVED** [review]

**Comment by harshhh-dev** [comment]
Thanks so much :D

**Comment by david-webber** [comment]
No problem, the favicon is a bit hard to see, I might try and update it later this week.

**Comment by harshhh-dev** [comment]
Not much of a problem. Anything is better than a gray earth :sweat_smile:

**Pull request merged**
